name: "docs: build and deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and publish Sphinx docs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install project and docs extras defined in pyproject.toml
          pip install -e ".[docs]"

      - name: Build Sphinx HTML
        working-directory: docs
        run: |
          sphinx-build -b html -a -E -W -T . _build/html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
